### ISSUE TITLE
integration server

### ISSUE THREAD

**Issue by gedw99** [julien040/anyquery#20]
Hey @julien040 

I was wondering if the Integration server gui is open source ?

**Comment by julien040** [comment]
Hi @gedw99,
No, the integration server is not open-source.

I haven't seen the point in doing so. This is just a [Pocketbase](https://github.com/pocketbase/pocketbase) app with a custom API. And because [Pocketbase](https://github.com/pocketbase/pocketbase) doesn't define a schema using code, the database is modeled using the GUI. Therefore, it would be hard to release it.

But if you would like to see how it works:
- [JSON schema of the registry](https://github.com/julien040/anyquery/blob/main/controller/config/registry/schema_registry.json)
- [CLI to upload the plugin](https://github.com/julien040/anyquery/tree/main/plugins/store-manager)
- [Endpoint to retrieve the plugins](https://registry.anyquery.dev/v0/registry/)
- What the GUI looks like:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6ad0ba2a-6d42-4fbd-ae05-3ceef1e80a7d">

**Comment by julien040** [comment]
Sorry for the delayed answer.  
I'm not really into publishing it right now, but I might in the future.  

In the meantime, you can probably go with a manually edited JSON file that matches the registry: [https://registry.anyquery.dev/v0/registry/](https://registry.anyquery.dev/v0/registry/)  

Otherwise, a simple HTTP server can do the job. The registry is just a bunch of structs marshalled into JSON. Here are the structs: [https://github.com/julien040/anyquery/blob/main/controller/config/registry/structs.go](https://github.com/julien040/anyquery/blob/main/controller/config/registry/structs.go)
