### ISSUE TITLE
any submit ?

### ISSUE THREAD

**Issue by gedw99** [julien040/anyquery#7]
All these plugins... I am wondering if we can use the same for submitting a change ?

hence why I called it Any Submit.

**Comment by julien040** [comment]
Haha, yes, you can submit a pull request for the `plugins` directory, and I'll sync the upstream registry with the Git repository.

Here is a guide about writing plugins: [https://anyquery.dev/docs/developers/plugins/create-plugin/](https://anyquery.dev/docs/developers/plugins/create-plugin/)

**Comment by julien040** [comment]
Sorry, I didn't understand. For example, would you like to publish a tweet from Anyquery? 

Anyquery can do that; it has writing support. For instance, you can push new bookmarks to [Raindrop](https://raindrop.io) by running

```sql
INSERT INTO raindrop_items(title, link, created_at, reminder) VALUES ('A cool SQL tool', 'https://anyquery.dev', '2024-07-10', '2024-07-20');
```

About Twitter, since Elon Musk joined, I think the Twitter API is very limited and doesn't allow you to fetch tweets unless you pay more than $100 per month. But I know, it's just an example.

(Am I correct about your question?)
